App/routes/auth.py
from flask import Blueprint
from App.views import helper


auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return 'login'

@auth.route('/signup')
def signup():
    return 'Signup'

@auth.route('/logout')
def logout():
    return 'Logout'

@auth.route('/auth', methods=['POST'])
def authentication():
    return helper.auth()


@auth.route('/auth.form', methods=['POST'])
def auth_form():
    return helper.auth_form()

App/routes/main.py
from flask import Blueprint, render_template, session
from App.views import main,helper

main = Blueprint('main', __name__)


@main.route('/main/', methods=['GET'])
@helper.token_required
def indexmain(current_user, token):
    if current_user:
        from App.model import users
        user = users.user_schema.dump(current_user)
        session['current_user'] = user
        return render_template('layouts/index.html',current_user=current_user,token=token)

@main.route('/', methods=['GET'])
def index():
    user = {}
    session['current_user'] = user
    return render_template('layouts/index.html',current_user=user,token='')



@main.route('/login')
def login():
    return render_template('layouts/login.html')

App/views/users.py
from App import db,app
from App.model.users import Users, user_schema, users_schema
from werkzeug.security import generate_password_hash
from flask import jsonify, request, redirect, url_for, render_template
import jwt

def post_user():
    username = request.json['username']
    email = request.json['email']
    name = request.json['name']
    password = request.json['password']
    pass_hash = generate_password_hash(password)
    user = Users(username=username, password=pass_hash,name=name, email=email)
    try:
        db.session.add(user)
        db.session.commit()
        result = user_schema.dump(user)
        print(result)
        return jsonify({'message': 'successfully fetched', 'data': result}), 201
    except:
        return jsonify({'message': 'unable to create', 'data': {}}), 500


def post_user_form():
    data = request.form
    username = data['username']
    email = data['email']
    name = data['name']
    password = data['password']

    pass_hash = generate_password_hash(password)
    user = Users(username, pass_hash, name, email)
    try:
        db.session.add(user)
        db.session.commit()
        result = user_schema.dump(user)
        print(result)
        return jsonify({'message': 'successfully fetched', 'data': result}), 201
    except:
        return jsonify({'message': 'unable to create', 'data': {}}), 500



def update_user(id):
    username = request.json['username']
    email = request.json['email']
    name = request.json['name']
    password = request.json['password']

    user = Users.query.get(id)
    if not user:
        return jsonify({'mensagem': 'Usuário não Existe', 'data': {}}), 404

    pass_hash = generate_password_hash(password)

    try:
        user.username = username
        user.email = email
        user.password = pass_hash
        user.name = name
        db.session.commit()
        result = user_schema.dump(user)
        print(result)
        return jsonify({'message': 'successfully fetched', 'data': result}), 201
    except:
        return jsonify({'message': 'unable to create', 'data': {}}), 500


def get_users():
    users = Users.query.all()
    if users:
        result = users_schema.dump(users)
        return jsonify({'mensagem': 'Todos os Usuários', 'data': result}), 201

    return jsonify({'mensagem': 'Falha ao Carregar', 'data': {}}), 500


def get_userstemplate():
    token = request.args.get('token')
    data = []
    if token:
        data = jwt.decode(token, app.config['SECRET_KEY'])
        print('ID:'+str(data['id'])+', Nome: '+data['username'])
        print(token)
    users = Users.query.all()
    if users:

        return render_template('layouts/users.html',
                               users=users,
                               title='ROny',
                               idlogado= data['id'] if data == None else '',
                               usernamelogado=data['username']if data == None else '')
    else:
        return jsonify({'mensagem': 'Falha ao Carregar', 'data': {}}), 500



def get_user(id):
    user = Users.query.get(id)
    if user:
        result = user_schema.dump(user)
        return jsonify({'mensagem': 'Usuário Encontrado', 'data': result}), 201

    return jsonify({'mensagem': 'Usuário não encontrado', 'data': {}}), 404


def delete_user(id):
    user = Users.query.get(id)
    if not user:
        return jsonify({'mensagem': 'Usuário não encontrado', 'data': {}}), 404

    if user:

        try:
            db.session.delete(user)
            db.session.commit()
            result = user_schema.dump(user)
            return jsonify({'mensagem': 'Usuário Excluido com Sucesso', 'data': result}), 201
        except:
            return jsonify({'mensagem': 'Não foi possível excluir o Usuário', 'data': {}}), 500


def get_user_by_username(username):
    from sqlalchemy import or_
    try:
        user = Users.query.filter(or_(Users.username == username, Users.email == username)).one()
        return user
    except:
        return None

App/templates/layouts/base.html
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sisnutri.css') }}">
    {% block cssuser %} {% endblock %}
    {% block csslogin %} {% endblock %}
    <title>{% block title %}{% endblock %}  - SisNutri App</title>
    {% endblock %}
</head>
<body>
    <main>
        <div class="">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary  text-dark mx-0">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggler">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">SisNutri</a>
                <ul class="navbar-nav  ml-auto">
                    {% if not token  %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                        </li>
                    {% endif %}
                    {% if token  %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{current_user.name}}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="#">Dados</a>
                              <a class="dropdown-item" href="#">Pedidos</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{{ url_for('main.index') }}">Sair</a>
                            </div>
                          </li>
                        <!--<li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.login') }}">{{current_user.name}}</a>
                            </li>
                        !-->
                    {% endif %}
                     {% if not current_user %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Inscreva-se</a>
                        </li>
                    {% endif %}
                    {% if current_user %}
                       <li class="nav-item">
                            <a class="nav-link" href="#">Sair</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </nav>

    </div>
        <div id="content" class="container main-container my-2">
            {% block content %} {% endblock %}
            {% block contentalimentos %} {% endblock %}
        </div>

        <!--<div id="footer" class="container text-center">

        </div>!-->
        <footer class="footer bg-primary">
            <div class="row" style="position: relative;" >
                <div class="col-sm-6 col-lg-4">
                    {% if sucess %}
                        <p class="my-2 ml-2 text-left text-white"  >
                            Usuário Logado: {% block idlogado %} {% endblock %} - {% block nameuser %} {% endblock %}
                        </p>
                    {% endif %}
                </div>
                <div class="col-sm-6 col-lg-8">
                    <p class="my-2 mx-2 text-left text-sm-right text-white">
                          {% block footer %}
                                &copy; copyright 2021 by rony gustavo rodrigues de magalhaes.
                          {% endblock %}
                    </p>

                </div>
            </div>
        </footer>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block jslogin %} {% endblock %}

</body>
</html>

App/templates/layouts/index.html
{% extends "layouts/base.html" %}

{% block idlogado %} {{ idlogado }} {% endblock %}
{% block usernamelogado %} {{ usernamelogado }} {% endblock %}
{% block nameuser %} {{ nameuser }} {% endblock %}
{% block token %} {{ token }} {% endblock %}
{% block current_user %} {{ current_user }} {% endblock %}


{% block content %}
<div align="center">
  <h1 class="title">
    SIS NUTRI - {{ session['current_user']['name'] }}
  </h1>

</div>
{% endblock %}

App/templates/layouts/login.html
{% extends "layouts/base.html" %}
{% block csslogin %}<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">{% endblock %}
{% block jslogin %}<script src="{{ url_for('static', filename='js/login.js') }}"></script>{% endblock %}
{% block sucess %} {{ sucess }}{% endblock %}
{% block content %}
<div class="text-center w-100">
    {% if sucess==False %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ mensage }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    <form class="form-signin" method="post" action="{{ url_for('auth.auth_form') }}">
          <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
          <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
          <label for="inputEmail" class="sr-only">Email address</label>
          <input type="text" name="username" id="inputEmail" class="form-control my-1" placeholder="Email address" required="" autofocus="">
          <label for="inputPassword"  class="sr-only">Password</label>
          <input type="password" name="password" id="inputPassword" class="form-control my-1" placeholder="Password" required="">
          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me"> Remember me
            </label>
          </div>
          <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>
{% endblock %}

App/templates/layouts/pesqalimentos.html
{% block content-alimentosS %}

<div>
    ALimentosssssssssssssssss
</div>

{% endblock %}

App/templates/layouts/users.html
<!DOCTYPE html>

{% extends "layouts/base.html" %}
{% block title %}{{title}}{% endblock %}
{% block users %}{{users}}{% endblock %}
{% block idlogado %}{{idlogado}}{% endblock %}
{% block usernamelogado %}{{usernamelogado}}{% endblock %}
{% block cssuser %}<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">{% endblock %}


{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
    <div class="container">
        <table class="table bgcolor">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Usuário</th>
              <th scope="col">Nome Completo</th>
              <th scope="col">Email</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
                <tr>
                    <th scope="row"> {{user.id}}</th>
                    <td>{{user.username}}</td>
                    <td>{{user.name}}</td>
                    <td>{{user.email}}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}